blueprint:
  name: Actions for 4-Button (HmIP-KRCA) Homematic(IP) device
  description: When a button is pressed, the defined actions will be executed. Please
    keep in mind, that long-press actions might be executed multiple times, according
    to your configured minimum duration for long press. This can be configured in
    your CCU.
  domain: automation
  source_url: https://github.com/snookerap/HomeAssistant/blob/main/blueprints/automations/homematicip_local.actions-for.HmIP-KRCA.yaml
  input:
    remote:
      name: 4-Button Device (HmIP-KRCA)
      description: Please select a HmIP-KRCA device of your HAHM integration.
      selector:
        device:
          integration: hahm
    action_first_short:
      name: Action
      description: First-Button (top, empty house symbol), Short Press
      default: []
      selector:
        action: {}
    action_first_long:
      name: Action
      description: First-Button (top, empty house symbol), Long Press
      default: []
      selector:
        action: {}
    action_second_short:
      name: Action
      description: Second-Button (person inside a house-symbol), Short Press
      default: []
      selector:
        action: {}
    action_second_long:
      name: Action
      description: Second-Button (person inside a house-symbol), Long Press
      default: []
      selector:
        action: {}
    action_third_short:
      name: Action
      description: Third-Button (on-off symbol), Short Press
      default: []
      selector:
        action: {}
    action_third_long:
      name: Action
      description: Third-Button (on-off symbol), Long Press
      default: []
      selector:
        action: {}
    action_fourth_short:
      name: Action
      description: Fourth-Button (bottom, lightbulb symbol), Short Press
      default: []
      selector:
        action: {}
    action_fourth_long:
      name: Action
      description: Fourth-Button (bottom, lightbulb symbol), Long Press
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: homematic.keypress
  event_data:
    device_id: !input 'remote'
condition: []
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_second_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_second_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_first_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_first_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_fourth_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_fourth_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_third_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_third_long'
mode: parallel
max: 10
